# Generated by Django 4.2.7 on 2024-06-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_question_created_at_question_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizz_name', to='quizapp.quiz'),
        ),
    ]
