# Generated by Django 4.2.7 on 2024-07-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_question_quizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficultyrating',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='difficulity_quiz', to='quizapp.difficultyrating'),
            preserve_default=False,
        ),
    ]
