# Generated by Django 4.2.7 on 2024-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_quiz_difficultyrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultyrating',
            name='difficultyrating',
            field=models.CharField(max_length=100),
        ),
    ]
