# Generated by Django 4.2.7 on 2024-07-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_alter_difficultyrating_difficultyrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=5509),
        ),
    ]
