# Generated by Django 4.2.7 on 2024-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_alter_answers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submit',
            field=models.BooleanField(default=False, verbose_name='Ready for Submission'),
        ),
    ]
