# Generated by Django 4.2.7 on 2024-07-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_question_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='submit',
        ),
    ]
