# Generated by Django 4.2.7 on 2024-07-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_remove_question_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='picture',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='media/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_question', to='quizapp.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
