# Generated by Django 4.2.7 on 2024-07-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_remove_question_picture_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='difficultyrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='questionchoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
    ]
