# Generated by Django 4.2.7 on 2024-07-05 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_alter_answers_options_alter_difficultyrating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
