# Generated by Django 4.2.7 on 2024-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultyrating',
            name='difficultyrating',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
