# Generated by Django 4.2.7 on 2024-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0014_alter_difficultyrating_difficultyrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, default=None),
        ),
    ]
