# Generated by Django 4.2.7 on 2024-07-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_alter_question_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='quizz',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='quizz_Qgroup_name', to='quizapp.quiz'),
            preserve_default=False,
        ),
    ]
