# Generated by Django 4.2.7 on 2024-07-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_created_at_customuser_updated_at'),
        ('quizapp', '0016_questiongroup_quizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='class_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_class', to='authentication.classname'),
            preserve_default=False,
        ),
    ]
