# Generated by Django 4.2.7 on 2024-07-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name_class', to='authentication.classname'),
            preserve_default=False,
        ),
    ]
